import type { Metadata } from "next";
import { Niconne, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const niconne = Niconne({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-niconne",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header>{/* <Navbar /> */}</header>
      <html lang="en">
        <body className={`${inter.variable} ${niconne.variable} antialiased`}>
          {children}
        </body>
      </html>
      <footer>{/* <Footer /> */}</footer>
    </>
  );
}
